// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA23D_JrOQjYQoV4a_jjBxfCi2e41AWvqU',
    appId: '1:80001120434:web:e021b2322df6f1786d71ab',
    messagingSenderId: '80001120434',
    projectId: 'tokyo-flutter-hack-demo',
    authDomain: 'tokyo-flutter-hack-demo.firebaseapp.com',
    storageBucket: 'tokyo-flutter-hack-demo.appspot.com',
    measurementId: 'G-Y2BH8KNCF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvieWgSa7EVQ5o5GobdIPLoE48QibQwI',
    appId: '1:80001120434:android:6c919ef3d76228566d71ab',
    messagingSenderId: '80001120434',
    projectId: 'tokyo-flutter-hack-demo',
    storageBucket: 'tokyo-flutter-hack-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByI0hPCkpX_h2QQV0hfiUbd_kMVJaOFe0',
    appId: '1:80001120434:ios:0796291133c36c7d6d71ab',
    messagingSenderId: '80001120434',
    projectId: 'tokyo-flutter-hack-demo',
    storageBucket: 'tokyo-flutter-hack-demo.appspot.com',
    iosClientId: '80001120434-u8qssl1mh0n0afqptl5gmld9jdmu2d7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokyoFlutterHackDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByI0hPCkpX_h2QQV0hfiUbd_kMVJaOFe0',
    appId: '1:80001120434:ios:460163126f575c7b6d71ab',
    messagingSenderId: '80001120434',
    projectId: 'tokyo-flutter-hack-demo',
    storageBucket: 'tokyo-flutter-hack-demo.appspot.com',
    iosClientId: '80001120434-e2k0vste4hk3hsi7n8piq1otrg90fk6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokyoFlutterHackDemo.RunnerTests',
  );
}
